githubConfigUrl: "https://github.com/joyson-fernandes/portfolio-website-v2"

githubConfigSecret: github-runner-secret

runnerScaleSetName: "portfolio-runner"

minRunners: 0
maxRunners: 1

containerMode:
  type: "dind"