---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cks-exam-sim-pull-secret
  namespace: cks-exam-sim
spec:
  encryptedData:
    .dockerconfigjson: AgBm+WyBFlmXlAxzbRmwykdvByfT5ukuhlpvWBU2DOY1kZww8Zt/FynzbY6NDyJHVwCbp6Va0G1KYpv6AHziMLbk9YXJ3N0/uv4BMXS2UOk4Ar9MIQyVu0l3JagqcPjV9aOzw2ICmHVQd1g1RHPeaTe2wAsfxlPGg/UL4agqvR7ACZ9ay/REI2ZBv8vIzzPmLq3O7J/vbif4D27y0970QFyImBcDB0foXS4+piY2UqFb93IG5OlrrZh2MVl1t81llwptzQNpteOqkyomBec/TDB9E9SAaUQO6cbCAWILs9ADzIZoFfFp39JracuGIVFEx11+N2LaathD7u/eFcoJfrmYWrvS5caAmm913eVG1vfVA7T2PBK8am3Xb0dMtwXsWGNaAdvXrdG1mhS/CSJQL/x38uq7K+LCLDHeskTiM9brixKfPa24iKHtK9NIypVrVv1oV1RFt6nZ3UaOHVVkICknCTpMTxo4GK8AJa8WrCZNSrWr2c/S/rvxCbYNy+90SWq53lwkaPjMTVFEVAPrc23R6vFG905H6p8wNf4GFton4xPlMIQrojkBG8Mc6MFrU5ysiiEicBLGSTt9yY9PlV9+ii4EC3TTZx5bJ7nJ8AzpQqJOG+AI2hfG0djCnLLkz2VJ2KrkfU2XoD362d1oZzey89Jwyzlsp91ck72RXeDbx1ia/7z9Jf7BFoI/DFqIDKn/rIATeCUxQ8y9BWtmz36FITL4B3vP/vcazLq9c4xEcIAAiXCxIW6hqYmAmF5fhsF13H4/s4WULADI0zs5vJZlkNxl8qi+yvno75WRvjLRNpl07bjQctZ2v8xKMe+1kbVV1irAEGvzC9LAaLFhBY4xJ7v5/PNLF8WRPAQe7lAvNqowBb/rpmHZM/eqKTrDpVzEiE5aBI/E2nr2OWP/zqE+6U0UsGw9Pbe8wN2uymLKhphdW/frl9Lv2R91UrdeWldU
  template:
    metadata:
      name: cks-exam-sim-pull-secret
      namespace: cks-exam-sim
    type: kubernetes.io/dockerconfigjson
