---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB8JlO3irtFKWG4C2Qn1RZ364Yo3gEAozjM+rjk5euSUWsd2lUCZkeg9JM9Y+3HgwmTJr6tXwX6FCQuGQvCqe58ers6yyAwt2EBAEwus9cc+qUcvp4BhKYeryxNxDXuxpJqGHLcXb2Gtv7iAVA839jUut4+BszXIEkeEa78UX8yZHOosnAwK1auNeOAs33WkEX5CC/4ASkIXTTSyyBx1niQiQuqllLJoWRzJSRZjm2n/3VFQsbxpK0Cxw4f/ybcw8blNPp22USuU/fXMcjZGc1G1l4wtGGy8HkaMqXq9euUksX8i80Dz8LcUin3D2RqK/bimN5OaTG7/M+mvymye/l+TgWg7CWRScyngdl7pvycAyGc6Ui56swM1IiW/KYRnFm9adISg1mkMxH7iUXSsqjv7H9nj2NX9p9mMgKF3h1IvDS72MjOPs/ymxzA+heXI5vi/V4zBJNrGQYks9h5NrVcKWgpPBIYzTGCjuZwY6OOBeYrYEsp35ll6FLHXVLRrN2kr3O4C7SQoS0Ezos8xxO1R/vFkcWEM9qIPQcobW8dsgfNctq3+4qvDwyM2rZC3Ikc42pK8ngik9d1czv9f2ikNKhHyub0mfzAQZpw5IIN581uk5tksoy0DZilP8Gr0rWt025Psk0bCmhXgnrt0d8XK/BzBPf9AiNtY0nifxRqIe4Of74j0NobhnIcqlyTHJltjU8oXHBIstamfpyAnTH/kFRDgs/T3dk800B6wyDXclLtlaLHzsmxjkiCKHUrc4qw9t/rlA==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
