---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cka-exam-sim-ghcr
  namespace: cka-exam-sim
spec:
  encryptedData:
    GHCR_TOKEN: AgAxH/Gz6QMmxVPZ8mxSNC5QIIhR4JCWN27gh3qGHNNhHvFUkJHBjDxNSz+febNrY0Zd4wCqbut48uCmHFn0vTGLfo8caFDQzm4YkMIX3l8+zBH9lvLEOtX3LV0QYMA+lt1pAClDcxd9vOtmZBHLznp7n6gy+ke26vm+7aELfFQCszSKv6mDOBwkhuit3kWkj77vOkcxF8BrzJy9lSRgh1Rgu2s4euDK6dqvj54tQPYwlnCXYCkjTJ80+P382n2nvdxvAc1P7x1Ps3B91GwhF0NEVU/zJayQ06nksNX2CypNk0mVLC6No0B2g1uYPF4ScUsN4DdlWExZ3z0bRcOMyzXK6JlrDirmZPX2Z5WB4nalVDpSpJFEg9HgbDtTtd7ABz6zOmPfiKpF3NFeP4RtoX8Qutt2j4Wb2Tj/TwtUeyZH+1OuD2fG14aEiGhvTTqxF8YDAQvIbXJs28yynX9zktENr/dfilcwgQGTjU2HQHPg4Nt7+vi2oPoRQ4J+NG5acPXE90i+AvQYjUyfzX81llJkBTdn2PHYzT/fRVORnK2tA/FA4B4d9IFPONskhrk1xd53591JvQhbcgR3T6B4PLhEec8sr37+7ofDYXRgbIb/BApUEjcLasVCJzMh2Wsvsd4lFI9d96CuJbu4bt7wN5M6yXw8UzbFUqzBbpAKxUBdrmQ0CTK5IPcMbDhfatDVKm6+jQadwJPKwlUk1Gkkq1MZELO/Hu8xP30hus1UT6VoXP/FiwDkxbmm
    GHCR_USER: AgC40izZtSNn06YapRkv9ObyamQe0Qou/+ICTgiPXtCM53zjErKnoekKiwDDjTyItFTlUPg6zNs3i7BJJTsDTVWXDtLbccDysGXddBVM50yCPwBfwVwbqtk4AjhNCBrt1mWryN5jHK8a1QjIyuiFjkqarCcKSA1AG0zQSHsLPERnHpmNt075mcrDioUtk75wh85cua3wdpiddetlz1xdI3ypxSih6bspSnbs0FWnRt3Y+98Q+fVZQuYXVjVlyrTGMuwhzYQ2Ns6ghq/clFilUWAdgCdBjiZH/xDKXx20PnG/4VStpWM+/QU9//BevocnCjedmpDu4TBvcwhqm9jeaoN2meq0tcgOK/GEYKrorhOZuM5uU2d3Fx+E40Uygpk2zlGKFAb54IM+tDvgjm2IK6remf/wGiZPTBKyjS8EeG6uBY1DVKvCHWHwcGJOU4JcRN5Gipsr408fMAn1ESyxSxaV9s6WqtP6oIgRJaideA75zF4PncJPx7Z+hWjrf5M8oDdTKWpdV4XcT98Xa35q50/fr78vZghPC0AI98mPyRVftFiy3yJTuc7oDv8iDyoxaVe2Ql1JlZSIW8Kskeeho4RrAzCqkoF5S8eVF4saFlGnAi65fORnbza4ktcEiz6pNmQp7I1rACSiSCpZ8EhYhjCmbPl3v6Qf3IszRGjbQVpDXjq9UaOLhmyEmD/2jQeTrW8RxHeRgocvUeUWRScIonAc
  template:
    metadata:
      name: cka-exam-sim-ghcr
      namespace: cka-exam-sim
