---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cka-exam-sim-pull-secret
  namespace: cka-exam-sim
spec:
  encryptedData:
    .dockerconfigjson: AgCOZ3Ad8/31EMbxzBsSE30UyPqLPfzwvRfYoNI9h4pGhNoDEvWtmUto7eWxvEsZrFSTaotO23z4P90voxVCjfpxfx9XzGpDeoOBpIAkxrGhLbEXddiL6wAKSCCDitFk7ByARN5w3ce8356fY1ByKEh1SaB3gI9QLkc1fXTSBSarcqvINr6oNvTIXlCELC9jUxGM9OyEvm+kop3hDD1XHG6zOZzC6wG/ew6HQ9AKtdA27m+qX5jx60nPA2iFZeZcUX0IUtFmIxWn3r5RZqIl9xEKfigDfzJHTpP+CM8BulydwqN8TNlGBZA9oqD7ffRV/ss98ewZ5htzliwjhX+X/HbAEqLn0GUR9spFyra8c16zah7p09dVJ5EP7a3m5M876VGzkYx9zY+BwQDlaTDHr2ft9KO4q8dZWukZqkb0Se/1br6bfZ/s/UOklN1hat++LpeKdio0rq9jyseaVW6mNjCmoK4LAx7AmYtV6MzOhruW//BPurhqYrrXRT2rdLQoRQ3XQ6b9W5i5U+p2wD9L8HIEL7TjAAWvXac/cCEAHSuyTQVnbJhKyHWI9I5+5txsDRNbzvL7j5ILmMvri90emQxJsWjzxL7Ob8tAzLrV2arfBg5OEp6pvlT1VddlMopVrZdfAZzEHH9u7UjJq1PCdr/SQOAoxnDfc6Ihm1+4s94pAnHHYyzJdYC7imrrniJyoXpsn+FpoNXLC2rYTZ66LPQmnKOI84nExMyS5966SXdo+0gfb3GDVooCL39hA3CScqlZ3YST9w23OkOYlQCR3KQ52NVI93eE80PB7MJCMGQq8UxnPdpdZA8TG2GAXqbFqfUdv0lryT/onJDuffb2ARDH4m0waQQjuuLu7Z0kEUHRw2y1RQBG9xSfNgoklD32F6LYUJ7GugXce1W2i37xS19agipffhnx0dIDBC/1Bx0aGNEowvoq5FJ0Y0eHLPv83Zw4
  template:
    metadata:
      name: cka-exam-sim-pull-secret
      namespace: cka-exam-sim
    type: kubernetes.io/dockerconfigjson
