---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: umami-app
  namespace: umami
spec:
  encryptedData:
    APP_SECRET: AgDWYEnBANqUR/ZONcraRQb7gTsWAJ43zyaVmbkZhUClii10+OA9a/1P5rVnJ4Wq7f+lTH6ZPDVeAu/ATdrGktJrjBYqMTuRE8A4Xi3Kdop2yRaAZfqGNpDKvYk10NQNaSuVjxwXF8CJyG2Q9juNV1KbDyw5yqLlhLmpLam5NBNoSDhNcUq3kme8Fxug3yt1XAkm3J3xJXgzm+WAR/F+gDnqtK5GhGs/DfP1THY1N2NUsE+ythj4eFzXqqn6nC4QjExlMJP+gJKkWUPZabS9j7kAkWgVTlI7TusyzoqP4FQkiXI7v0biZFg95SWWXQsMuBoGlcBmPBPnNg/xDMDQzarTgYxgkQQDEHLTGvfaaqpQGyUpw+eu+VYYBCC6VlRPQc8ZIsD4p8ED/M1XuGfprT5onywAEbZ0On3fA6DtoX3mL7RXiIcaab0ZyMc2Vz0bsUMl0vuh5A1UudCslmR1+8LUFVXaBYh4QJcTcHcCDWiguLg96+DlbEPlf+dqDnlLqzS1p9Xs+MMrFVoqQ7TOFBnw4NskXVC4xojZ4jWcJ4gwGE+CkTgP1/9pe7cYOr6nm/jEFHpOJwVvRpya1JvDDZjS82jNYpI/ZmCQZFceeSE1+BPWOYDueXGg9JgOI8gKtNiHWmuGcRBPVv97KLI7rxWiXZXLDurV/4uP7zv61mqEqgiwgwWUBcE9dfOPS8YYQ6XvG3tO8T7XBkvEmeqcYBqxkH/W5iQba0iF3w7ic52uSZnd54Ec9wCpuTrr8Q==
    DATABASE_URL: AgAUCVTP2kKJ4Qb0ci5i1McHRd48BlU+DB5TcpD3yJXA1bmZZZEaGYGmT76FZwuQoF7usmCjX/sPwr+5xald9RzoIRadV+XKXeudEpy+1n17pgNqy/4cviswNEWUXeLF+53zgfdOc7cQYkkcIrHq3VDuqA7R+yCUr/xMZrC5LsBroRbs2KHFU87TAforuefeCYyNeH90czJIQ62jXJWM38jcAql4VCoHmVV8fI9cMPJDMIcVbaMPTnSRpNL6h2mwKnYx+vdvXV/jJOCAnjA58OOFiNqJHgB9EXprnt+hU4WKHazTy2zUpuauowSxYrQDzWCLBP9peSkKm+o49eb8tIdAYYjtZgrlTWvOV2QQ4ePFTHb2/zwq6gKCILF2PEpvawPedhBX2nQBqNMfjwR/HNErZvgy5E4PeRvZMj4RF73lE75f6i0FzvTfghD1xXcV59ax34dSDI6O+DJ8j6xuz0ZPKsivro4ktNWGIR39ACv6YiUDc1O9gBa+nUpGDO886e3ZTuNXm+HgaaV5hdIuDWB1XV+k3GteIUZHWw7bFKrDjomTayJljE0S53Fulp4enX0q/u5+tT401Vp7jupeIrXVkQRuAiRWMMnj1R4aXqtZ1L1X+j3EH0zslnI0+LF4KqyJbC4PpVhYb1tr52rKXty7PvD52UPuOarE70IAwZk/PMeTIstfMpMvmz3Ekh3ThQRrDqoh1jQu9JscwUksMBbTNx6US2J6ecL3tMG7EpXUz1DXxAdmm0zKlOoMb0x/S31uAPpApA9LDrPW2IWwKcaDDw2bXFb+7d1RhdQhhdi8XSXJwJLTsQNY5V329wo=
  template:
    metadata:
      name: umami-app
      namespace: umami
    type: Opaque
