---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: umami-app
  namespace: umami
spec:
  encryptedData:
    APP_SECRET: AgDb89IDj4lDoL7yPXDe0uVo8hKboRwON6stRniDe4WnnFnNdxCB0EAJG5c81e9CTSHuyqeUcZhLk5KqoHfgTKm9arbuimoX5w1r9hct/Htla0TKkaAyk1b6AnO1plQ3Lbh1pDxc3B3KTvj2szfRPFC0HvviyS71YvhbyjKgios63PjSJvkXeSkclC0L8lMDch6Ah5tks1UakkgL37MC+VDiZe6X9S3ajCS0eZ2GWKd7p1kQRYYmonry1MxPH0PI9TVQQ1N9FY/j6ryyxw7Vso7VOY3dr+IOG6d3OtD6htqrtru2UPdZb+GbOF9vqdEQgqjj9pOuaKxuLuodfotCK0v46ZIxU1I8OMpZHbrpBd4dy0Cni2xsc8O40pfvY0YJFMK9Sa1xEFGDOcVJO54axntXmWj+HhiVLZATBF1BfJi0WWFnxbTmpwJICMXZQxlulGnN3lz/yQjodfCEvxzTF+o43a5rHRW3ry2TpuxZ/Ck7W0DBz8ZVUEqhlyu2C6+4lc6c0WjIllTxJR11/kYyg4LL6PhcwY6DS+liNp4TYd9ScpUmyDmtuSbg3QSKLTt9BvC4paepV0XwjokZVa4ghhJbrQo2uGUU9ifsXu+mv0rDMXmzymzk6RLPlGZKLfizW1TBhTQsBpmoTB5c5EXo1rhMmjdB11qsMQZhZQT+U0STQLdXqoZyXqMVhTWYHcFtTh+PkPILlh2vFwirxIcXRr8J3IbxR/Hvc/Czk4SI530anpC37yD4Capzcu6BCA==
    DATABASE_URL: AgAdBrgs22LPkgn8nZXy5izv5iMf8RqmfGHGmkZh2M7sk+aEK3WRq40bCNPaCZ7V0cvNTy3KyzIzFmBt7u2Fj82QlpSBob/d7jzldr+TiVdQPURGF9WnfVhImSSOV/zyU5MK0QtpmAvQ4wE47WtajcRKavD1VaB/uJiuUiks3zSWQS6mKhFsObRGYiKD8kEZpPhtgJDathASl1EoKuwWihMw+7vV2XwoAWKHp2y3z0ZilWHpIBLZwNPvS2DyjCtvbfXPda+UK/xuHHtLZl1Dn5SP4zCj4BFNRw76nVDzSDdTqnizy2f1guvIgTlx9EgS9hutNRCF6xSPBUjtKC/la5AWtK2usvH7dDlByqIHIg5gnLk71G6KjoiSZfEfw+8xVfmzS3G7i6azXVqBcr3MyZAiBtDPxO79sDaADj9NvujC8F1Ydnw7qRTc/ZycD7LZrxIfYcJhUL3As68pX9GQgOAWFZrOAiPsBwJCAuN+Ue7GT1M+n9Tkudqad+h+HoecjE1YOXSPeKO/BTCBeZ0U23Cpy2FzQCSZwZeaCOnz8fwMaeLT6a/OeeGrnX/5EfnRHzwEZDYdV7Qd5o+rp2lfzUqo9u/CP5moagIYrtS353+5hg9lnOAHYK1WEACVDO86/RmRHwaneddCiYWnDTr9m9HeqHfQOTilrk9adEv0QG6rDjwCNE96pEZlOcGtH1An7G3eefb6IY/t19SlgwiVt08q8262cyGotE9fJErqPKt79dPInjMhw2h7ikvvoikqbcPjk+oZwWcrejPnb+Y1cOU/we+L3r9Z1ciX66trLPkWY70T/A+Ik8w2TZDeXfvo9rKNEmtz5vivciVHSnoNuOpke9wctdyvTXLFWeR0sgi4qTnKRg==
  template:
    metadata:
      name: umami-app
      namespace: umami
    type: Opaque
