---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: practice-exams-quiz-pull-secret
  namespace: practice-exams-quiz
spec:
  encryptedData:
    .dockerconfigjson: AgA7iMHOPHKFMNtEQzAPtdOu4I6DEnXXTt8loS7ZiphsHORgr/tqwC39eiIzPWLCX0x9V9d5YiHUrvTNSf0zn6pjg4KImFWvcGaVlPeNl8WJU9MsVM/Ky2fwKbqqUOCdeNxXhUngMAkB0BQhMQWi63eDUY6kWIeOwiY/AROp41S1+LwsXLnXZlKrgIpzkBVT1gTMbXDSspZ2qyCMzjeDym4sUINcsEiNc178ShKYduXTj3+U8D5C+sZZQKpR+UgyPkysp1muvM3k6INMEvuZqlF0S0Yn7ljfINZtNepz+qTGD1G+HpW5DyJd7K8yb+eyUxt7A7YZElqbMlK8bUsE2NhfeB6ZmN2IKqX5dfLmXwdM0q4IkF6KYAqA4UkdBx+AfqzcRI8jvdImqymlG7g7rSGlfTSiB8qJXYb4lsPFtpRLLtXDcn14B/xYvJVdGywi82p29CZNQv42NVoGGoTfVbV+v2JJlBoUkz/12VQQF0VlsBKl4bYqprzXFt01MIRN3/yk1f5W3XoOZX20zgiOn2Ah04ZnobPLsSuHdffPnWgIb0sDDmU/C76mJZJC2/uoRVfnvbwnykKNukygtfPlv0RRYFNn1MvGi85889Kd1AEYB6yeRauFzSWh6/XqPK6e4piGVT3gpUxyg+f4A28WOe3cV0p03OL/qDUHxShA0A1B4K/SLJOdwrj3fweBtTP+bT2E0SxcPCYUU6l3iulfRoEli6h1tVQBv0n3JnZG+nwIvqBQ2QalybGfP9mgbVQhOieCAztKAFXDa9RfmnriFfxT93mMVK9rGBc+BSr4VqkHYWMrGay6u+MClUfsPs1PO5tbKavO8dEadYyDT7gS0O4jBFQf9Wz6RZwXEhwNZchhakBUWD+JZZBKJkSMki/3eL1W6b9+DhVsAAw/i3zBm2YGBIvHGUFgd8IF2BHwp2/HTvV/kCq0trogtWA9wUALJsDv
  template:
    metadata:
      name: practice-exams-quiz-pull-secret
      namespace: practice-exams-quiz
    type: kubernetes.io/dockerconfigjson
