---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: viewlink
spec:
  encryptedData:
    .dockerconfigjson: AgCLomZSCVSd34QmbkWyOejejtUzJIaORV/Aci5AxAvfC1n9aDLJedhnSd9QoxUPBRKT9kkUQR3e98D97e3+dftvbc7B5P2a8nQN+rpAGFmotzC89shfBE80Jcitj9DSqot2foANVQYJIrvywVeWJ+/BsMcc8ehjJH/7xmfXY3MS3tEOYfO+4ygHWeYbOIMsQ/gQ/VfCsDdSoLiY+kQvd4u5KwuFAuEhHh3BmLp+0RlwSbtymY1X7zERpT81of7LNpQLFNb/B3SUIdwSUf0UV8263gRAodx150bopMYdA2bYkRpbvyZfaq+ddHi9LDR2xdyPzkOuyDALWq9yn3ZCm+6XZS4XZoRuIBSyXhzwhtuE8GaBwvILXBR4aFnuY0pgaAYxIK60ORGdxQZwK6U/JRyJrhRPaL+JfE3306nF2Cl1h6vrZpJftx6RL7LXnGLgMOoYyZc6vswlPAmGRBTY4c/WxNOehLWUKGzQSzN4l+FdZkYodMmstkcQFuDIqyRZCcf8dNaDxYwXNKMUL6e6wlgWVWKJtuS3yBvafe3/Alw7z1zQxIHAwJJQ07pg9QUJ3xb89IToyfJkDUMG5Xdn1TvrJ7QTsbWzEYUYwOPxrqZ/nK6TZONTodhQ3QfH4lY/mrXEDSsIVibJAcOXihunyTm4OUzqf/EN7R+tIPgMf0BgdyYrh4jqaXFvTl+3le5eQLLE/6s6QTEBgYypUDp5ZOAM0bRBAiBVMcRNKb6igpDPZ30Z80xKcIJOOpNyc5ZaXtgZOVC+LDhE0CBpqLlzLWFZgEqYbkFCZoNPZoqJbZLiLH7aNmFtepf05iiRw6U/lEn0lY1r+yk3v98Wk8wQm7K7DrVoWUf/UWZJE0mlbu2ybBBHhUjVX0QNyl9DhUk9umvqtzOP//4cJ5gQNGwHWHPJq6CuJjoN3Zky5K7Am+I3EC0KZY0Yfx4dOKvqGDGtn8hV
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: viewlink
    type: kubernetes.io/dockerconfigjson
