apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: phpipam-db
  namespace: phpipam
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCbCUKCHb+VuRJUgniKeYcWNqdxaUGC13LMq2QXhFQ3Kq7IYEzxNRlNncbu9kNqsS1Y7OK9rDRZyFPPSjDebkgaaCydbtktYY7z58utUdwNGEthrcM028x5rMYcdVAg/EzzzTXeVISf8NnKb0E9Wz/AH4QyjETIc/CnB16GSUGv4ijAd8JljVIX0AjIDOE9qL0l9BI2zwiSrvryMpDjechTS4p6tbssNcS/LJepgnYU1R1sa71g3x7texbHPCFMoevSjUtI25AMQcXmS6G9O1QCgw59XYHscGrTP+rh4IDiDgcaMC7YSfeeVvp4gMmBvVFbePlX08lAWKRaN+j5GZowsPTNc7ikv6YH3vM8pq+u+vqRqV9l2Cn3XnTeTI4oxRVVTUYLg8xmtRIyuphoYVZKzSVL2dJWMuU5zBpwowQ2UTVOhJwq5ZcfnwPrj6AYYwwrzXlK4UKh2PIZp3fGmclUc5n3U/fu3FZJAa9rCsc4h4wfnfbouYok1otPpobbEje+Qogo5fEp7rblrmzdPtwefzkXUCveRttaXE9bAIDLh73TWEE/wE+NxR+9gBQHNnOYctfB5KAWL6L0PnirnIQ/ezMd0L8LfKK30QRKqkcNdUgd8btbBIJMERt9RIZaQpO6zLq0zKvJZSAXDXDLZdS00B9+2fzXOoc7YPBDkfxCzcO3Sn3+8CAYuiZ8RMtoRgMWcfOwOshAhhF0LyHDwGE/Cry4MZFtrvJpfblHT1gEhdWhtXMDlYxa
  template:
    metadata:
      name: phpipam-db
      namespace: phpipam
