---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: homelab-guides
spec:
  encryptedData:
    .dockerconfigjson: AgBMqKaJwTb6rtElA6s0q7/HoWaPKPi4IsDxeR8dC6PdJzN8AJrEE54OIfaZRcXcNk5qRf8EhVZwMK18APsBPhSv5nuY7LJ4P2mi2cblNjkJ6AwLBuvh63rX6kY2Qjc2hd5JFxUzKzQSX3wu85V0q/fpsmaDs++OIw1+DnHmHijSGzs+ko85XNW1Px8v8zYABsQ4vW3AOox0vRwhSUZ6fSJt9SodvYB57RD0Dk4aMThxwgUBWyxwt1T5gdKCz0MueIt8+FbD1ryNZXDFMkgULX8LTnj/jlYoAjHs06C7cYwVf63FwsDsRVvWvEi6xp6Odq2frNhUwjoZrRhq0zU+mXJUYApBHtkvP9SzKCJc5UOguhbQ6pu3hUaMHx5/FlN+lXvfgGNK2+3ZFVdXBINE0ac2/73Xu9vvO1EhrKU3VaMk39kutztXjiYogDc/JY/6jg1BhJDK1TnQAPjss126utginmy+DlH3I5aoW4Fd/gr5XuEbRh+gv8V1CgX6kEXNf8+Goy8iXv4rwCkF65JW0u/VT6CN5li3hTY33YpjkTQE6d57WpZ5uZp1mM+rwwB/u7+mUGxDoCVN37XKyBrv9nwdwAsc7xjmglGJ8uPzsyE1VGkcc30gL1qXQfmlNZaXSTDFWLWdwQDRuLJFO2NXTRf9H8qNFHgTLt3M70Lx3swtBNNzVwgoH6YpVfdgSfdeu2PekVoY8YEA6HUbD0vy7oW6DsXlabXuB1E9j/MlyxbzV3B9KJOazCLnq7zJIO3Z00EgODOeLaytKH6ks5DNs9DMPexQnjliEc/SIwXcRzw9411Vzt9/XhwOUNBmbtzasIPG3M6pYJVkluCfMbwPe8ES2BZXPvVZ46S4v5C3r0at+R/fe5s4A14XrTH3/hz0aqZ6vP9vrbsOerP4FdTdEpoFUTQMCzvOGa98m9yiWGJ1C/Lo2CZPICQBqYYuMX7f+2YAo+ifazCIElDBBaN6mnm8cmrsNJQPqRvcu37FUA==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: homelab-guides
    type: kubernetes.io/dockerconfigjson
