---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lfcs-exam-sim-ghcr
  namespace: lfcs-exam-sim
spec:
  encryptedData:
    GHCR_TOKEN: AgCNGBSGK8qw3QO4oijgbKqGgVm3s715JVIMQbFRtwJ6BOajmYQuP/qvD3OEoPd1E/SpjnmOCsHLUFCyD6zNYuf+uQDO5tqILy8bpdK24QPspVEmig2L/RuiTxC2SwdedZw1FuYXSJKJdCnr9MJaByMlZfm7za4gnPIhVYbd6/XlNy74In0cQ6qu2ilD5cy/fUnvfwwHxaBuIIryVqSxBKizNoF9P/57x/uQCzCzva+ZfWLLzJIXIdEpEU3lW+fQdyur1GzZ1MvBGJFAieRSijTPf+uOC3X1shGUmj+QPIEq05VVfEWzAE+F9BxUqJbS8NGcsEHjpTkmuuQADhP+66MmdRCMvmD64QKt2lVgoL4hPV9bvIkuDWtmHPhrEUqoyJkDFj0y6w0NZ3sYSsaysaAfmJ10AzR1sUJBj5Ptb3fzEfthRA2yxWitImDomAq3fvnLLHwy93ws2ug4Wjr94uDGtgnjb6TOcMULEd4TgQtqFQb072g7D91aEWGnbJNQWfJPHl1Yde2gddJ6yuV+gthMvrzCzfiM+2fYoPfOCZUn0voZpi30oUwDFG0rKmEM5SgFC4PiVsXh2czz6s0MjhgxwS6qMnOt42qFLe20e23wBFcR6VyatYOcyFPuZ/vHQ7CohqNyQqoMGED3IAfZwjTEbz8eXV0RjJuz0s0y9SQJSEdwZo3l4IDVajFrBXS9N0GYoCzIsp/zmHHI0uGoGMaEDvPLtpqm3z1MJtv9l+fXDCVJz+N2aOC+
    GHCR_USER: AgDM9in8zx9pbbt2tBvegQuBcROEXZGXXvTBTVOY/OPb++3/HudpFV/Pmk2jG3VIqURe7ElfcvLx6zgifZ9OZG4juPnluESAE5DXnVKXMriwt47NNUuVhOdjWP60Qy3Qot36laKPKAaFNdwdnwy0k0mpHGZCXRGAo15gTYJJrpeN3vo759okpA7m3Ow3hbASjEOHcsKJibzGU9rntIqzydQgwGiew4yLQSAnWd5PCFC9k3kZ6Yp1tSAOC6Mnn8GlkOeplT/TJNeut5M5dDsr3xCeuXhb630Dp/WLix9ZSicd3fKMKumm/0i3qowi74w+npa/hbjuynmEhtmb+YZBgy7vWlpSxpR3w+fK6iv/C+mnJYK1Heal4Mzhgdjx5vCvypdP0OayrZLGgfD+zWlMzyAtyGBjNkX3OZfA3+uyE7zBzH5nN3Jy2vAG7vEtTaSpEz/6CB5nWxF+B2z21rDBHMdcUmpyjZVvKSYu8e+/azUhMESdNQnVhYQVPgyKZscCSPDp5OkOdLKBvu+0A38FGHdbm1NPudgvp+V6cnY9ikcdbjXaoDEqKVBAszu0ZmBAb+h2o9CoqErabdLdX9NTRK2PxxutljRS5H48hSfEmBa+2PMMauo9UE5FwltGgwi4rbNFh5hhXNY4MYIi2WTUbI46d/+IA0piRd8ZrMBVRGEy5uMxkllRmabkN26TDyTrRFyMXxBF9hnSWcYjszr9M8W/
  template:
    metadata:
      name: lfcs-exam-sim-ghcr
      namespace: lfcs-exam-sim
