---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lfcs-exam-sim-pull-secret
  namespace: lfcs-exam-sim
spec:
  encryptedData:
    .dockerconfigjson: AgAwKqReq+iZi/4tEhPlfx21byHfM6NFFUMNzX3+qbevI70qcwSL8WbDdMyiZWwHXk2C+bdzZQb1ikDFEmEn0OcvcP8Z4DxCSAqchhkbwQmK/EVM1p1OCWjALOHCNpZunnYMdPlh86XfTBHy1O7CetaUAVaa4VRVilV5ezmjMmFA7PZtuyidQD/+D/dTE0i8gJ94N/wG6WDqVVDjG6WOEefVozJLoWOdapdoCrvXl1WraNHSiGMFwW84At6DIgLXpw7VmOB9eb4ALDraeZMTnNXs0jwV0fPhMxe/aCiUQfcIf5GHkjTaJbgzA+DZqbrh4irUYEJ9onuu2aPHEYbMYh97c6vFTQQM7VRdiWQb5m1pUdA2G+ia7qcWshqT0ZUCDnBpggrXXBKyTGWRwPGDgW0WlJQwtIymUj774SzAQnCVTWrB/nmDyund3nGF6VvRzcd2rC80cQ2/5jdbjFXf/WFW3ev2na8GrfpMRI8EmcZ+L97dETfzWCVJ+FcpapxkN6AFB9WQAcxMezqXU3jFMocDxk9iNj41Cz1LzOLmqy5ij6VIRdC9AXrkEM8oA6qdSgOrBv5dSRsD9ULu5OYyZzEi/bR1ZzlJ7R8FIupTmEjN7VFfUMJbdZjVOgYNTM/FCEryUyhp6g2rp0SNtxAZE35Bt6Qldvw6RYeHMMHeGgUoavPqICa5xQmN5vX6pX00Y5dXBN8WBR5S205DyopPDazn/1nYCNV0Zd10Y+tUfPUVHbtbFZnNzt4auqduT6Ryp2Ds0vg+CXvhvOLmo7GJDyEEcgScPoWMkF/tWNEYA+zqKsQq2Oa19mC6u/U3lOWKl4S6PQ9o1CDD5M1tAhwiq/AhB/2hKgKGjgpLgq3X+3aOcBBZntUubGrSZaBjrnpcbDmy08p9/OtJdjUP2AfAAawH/dwl4AWdg14W/3aJMSR9ofo+sU5tqFHh8tYy9/3yCzF1
  template:
    metadata:
      name: lfcs-exam-sim-pull-secret
      namespace: lfcs-exam-sim
    type: kubernetes.io/dockerconfigjson
