---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: practiceexams-access-pull-secret
  namespace: practiceexams-access
spec:
  encryptedData:
    .dockerconfigjson: AgB5aj6UiRiWHquwVGNlnMBzh8Bp0T/+z8XfpWjM7t88DV6Zoz0aa3p6Ke54qKMriy8wFacvA/BV6Rl7BQhEDzrgO+cT8xvL82DP6BDWSxmn78DxhOADsvrtDp9j91SgC1w8q402FLXB+i+rnEgXB4pn0dONoLPxU5D80hbDRQ8pHEASSQQA4TNveNhyNf5Bz8bB3b/gae6SkFJYctPIGTmDs3p9bJvEKmXKhKg0J9Ph8E8hChl5nI9GsOKJq9iq+XZu89E4n4eiLNZgj4ANINvLdMZPteNZgOEhnmzullJThefmg9YAoiKBkiwpsknhekDz0MfHR92GPBmLwWbWFZxwbKV7CsAwqxauyDbrbeN4R/LqXGlWpPNnuD++sA9j/jFGD4RDi3OBG3OBKK1NzNwxpdGaOvUca1dCDhoEAuzyJJur8/jsJwHsyOcfEOOiBeBOJzkJeCfmRz2/ck/OUB27dyca7H5ndqy7MP2cwPcfx9vVT595e9bjkqWrP3c4k5p3QuMYcI35MvsHbF2m6UfmqqVj5Xo757jiNGfZJvvQ7bWc2A6TxLwGZHbl9ImJ7ice3n2TMtKSasNO4Y/+rKQf52kopxApwEsWdjqVDiB3DgoN0Z5aDWwYZ9uqe3153S4hgJD81QTcb97YBsssDa1Gl+rhYHXeNKMclF0ydIklNT0UZIcFs5KX6c5+Ua5a++/86bthdVeCIa6umTTWKzsdmZ6iDKONQietSbeR3jm0raS3Chj6bJXxRw4Mi6RU/BquaA9aiFb/3TBTEVCibnfd6240ba9rV/xDRsndhFqlq2FVOVeQ0/D6NMlAjcZPwz0r45POxp4geQp9qGpvTQ1AzdbR+zAVt3crQGI8j8G0XtTRBKC9Cbs3Qtg0n0gfp2TPhvSVuqIbRrUU5mZifX+tcerf4brH2TtgJ/yburw0vMR3/Ms9yMBlJ6GsWjJfg4HE
  template:
    metadata:
      name: practiceexams-access-pull-secret
      namespace: practiceexams-access
    type: kubernetes.io/dockerconfigjson
