---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: practiceexams-auth-cookie
  namespace: practiceexams-auth
spec:
  encryptedData:
    cookie-secret: AgCVdKHHPraqbNQgHBQzbpkr9FyaHPdHsdX3uVNIxzfcKWLZCi5RRXr4r36Q7O8y+RhFCprn24yANWplRJPbTklvlpAUI03KtiEQFsfvwwqE8xdMtrtgJWn9jGg3cnO58xlnP2F2md66va/qKtjw2dbEdeX8/qOSc2KXL4v8mXRaiAPJI6oAOAtSlgFWvu4BHhjIb58lGQcFcJ+O7wZ/JYJn4Nb7qT/nkIycrTWpl7vEWkkfv9OjxZwwJBsnjJLoR/xP6NmlgQd7wdoT6Z4qmIpjC6V7zJ9r0WXf65LLqGocIF0M3OX3Pe4ZLrEUWbkvEKhSFs0XY03nIaL1mwUxMnbDQKqVeewby/8kvsA9CxTpwPia9hv/1ncPaFzBi4WE2Jef4wT2HkcAebDaRqd64ss6OsTJjHKpLT7RqxX53HnP358rff2QTO0d5Ih7FmwakSYhmZi4UJnDxjoFY0WC6+Rk1s6UWdwQx/5t0Trnn6HkRZ33TSaNgmwJ22ru2nq/NxU11xLAAqLTtVy4HhPQNJ+MW7695IYgzfOMLd0691L2bdHId/2ScfaK7B3gOkyezwHnW5OCLG2Z64rJTT4idYdehwGr40yErr6hgDNKqMesBNRyoIp+xQrLvHNxI8kuLv51Le3HK0oUR043wDzwt2dDEWHiwsPtjDKxwutgJMJ14wGT9LZwXYYubF4WRecwJfnOAuEyw+0nuyOxZJhmlbAQxXSqCA8NOn7DCnWE8ZiP6ScZPN8gT+HRBXjc5w==
  template:
    metadata:
      name: practiceexams-auth-cookie
      namespace: practiceexams-auth
