---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: practiceexams-auth-cookie
  namespace: practiceexams-auth
spec:
  encryptedData:
    cookie-secret: AgBQEkq6zr9aTQRNEDeRBy6bw4ZOVEmpVaYIUMVMja4P8FCHtq/I2iuEVwtNq4zlP7E5glWXgUhO2tub6biq9p6crN9B9m6dKKyq3EpK0MfQOCKxYYURawJm8VMWkzFCuypzYYUp0aOpdAsrh8ZldsLdiV0aUV5jceTFmZ0P6OJsl/GnOyF/IiuWkxNE2iTBta7Zm4IpqzX0UVvXlFqmcFb4wC9qCT9d2YAATR38Ib9H7XqF7atfvyGYnlGgqwHL+REn8cm+bmLVWjHHKuBA2DsBxJiZ0jtEBcEKO4bavyMVJfOQBbp13XLkcGoWIAdY5uNolPlH8pz4+s+rrj1aRMUF9U1+BM+gbndJ/LmFrXtqbXBmZ/eORXBo3EiA0and9u+ZIc5V3r4/e6UltZgd5eOw2GJMqBfgNYB1+aYR1I6H/HtkH8e/P+tYuHqk2cx8KuHidMslyXeFso/10n0C5BMuCtiHhjfB+wFu6iyaTKeWlINvppCXnx97o3rKvnzfWL9fKMJCWbnk4KMcM0Wd0kJGLzgbhzLAUaYqWm60PTvUncwGF7X7gJlF5c1z89txeHDXbmlWK/0L/EbwgE/YmE72xmsvHCBYBfpbSvQgS2GQ6ZPDLg4JbAtnhRsqAvdG7EqGKDJXsy47bTZdF4L3/m+kDphqbmkEjIK8f3BRP3Acu/u1KeeS2EDyjq1LbEvTnBo0TyQFIPW72pInVoI2yqt4KszDVUkXSLE+C+TpCFdRwA==
  template:
    metadata:
      name: practiceexams-auth-cookie
      namespace: practiceexams-auth
