apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default

  sources:
    # Grafana Alloy Helm chart
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.12.1
      helm:
        valueFiles:
          - $values/manifests/alloy/values.yaml

    # Your Git repository containing values.yaml
    - repoURL: https://github.com/joyson-fernandes/ArgoCD.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: alloy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m