apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems

  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    chart: gha-runner-scale-set-controller
    targetRevision: 0.14.2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - CreateNamespace=true