apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.14.2

    helm:
      values: |
        githubConfigUrl: "https://github.com/Joysontech"

        githubConfigSecret: github-token

        runnerScaleSetName: "arc-runner-set"

        minRunners: 0
        maxRunners: 5

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true