apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-guides
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/joyson-fernandes/ArgoCD.git
    targetRevision: HEAD
    path: manifests/homelab-guides

  destination:
    server: https://kubernetes.default.svc
    namespace: homelab-guides

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
