apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 90.0.0
    helm:
      values: |
        grafana:
          enabled: true

          admin:
            existingSecret: kube-prometheus-stack-grafana

          service:
            type: LoadBalancer
            port: 3000
      
          persistence:
            enabled: true
            type: pvc
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            size: 10Gi

          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: ALL  

          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki.loki.svc.cluster.local:3100
              isDefault: false
              editable: false    

        prometheus:
          enabled: true

          service:
            type: LoadBalancer

          prometheusSpec:
            retention: 15d  

            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 30Gi

        alertmanager:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m