apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:

    # GitHub ARC runner Helm chart
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.14.2
      helm:
        releaseName: portfolio-runner
        valueFiles:
          - $values/manifests/github-runner/values.yaml

    # Your ArgoCD Git repository containing values.yaml
    - repoURL: https://github.com/joyson-fernandes/ArgoCD.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true