apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  project: default

  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/manifests/arc/runner-values.yaml

    - repoURL: https://github.com/joyson-fernandes/ArgoCD.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - CreateNamespace=true