---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ica-exam-sim-ghcr
  namespace: ica-exam-sim
spec:
  encryptedData:
    GHCR_TOKEN: AgAuLIpJfz8lxU8aGEIg99J1LrtRXCw1Z9u9DkOx80Wbr6yXFFk5mqDMgFuhR6ky5J0+13DbuxzXyGdE3SFjANp0q4QoQSwgwFGHxU3rulkSeoN/iQFAU4/Oj5DIsvw2S4e9wKfqus/bCQ9+nYgRBYmxdcNrMvRJCquWA3IpC36HtQX0qDMPy4TcBgA4mqKXN3pldqu2Uy+Hl8hpo6c9wY5xUWzbG4J2pv5C9fny8HmC1oSAvZETNuODrGobEdj0humrcCmO+U2+y1wVMCBAC3edjLeLWh/BIqUECVonkyDevD206Iikrgfg8NNYWxqefMZ9fWlPUG4u0Srdnq8aNJEpHj9rT7kB5wQeKBKhtDEhkqgGuX38W0T0v8ScK9RncIWGrfDH7GgOYaCKLGVugexCV1JsrfHxnA0Ia51b7jHWwVlP0vWGVp99w1eUzYE4bJ05WPe1D3Rpq/rAKR4Bgj9re9N+Om2YSZB8FnCw547NUePeq6B16layyMD9GfT2UpqKKLfSxDLCN9vWjgnI+M/TePzIRmTpukU7ZBRVB1rSt1pv3cAUXysdx0qt0WAQLFf2XnnNBV7FTzqmHDKZW999EAuuorI+XFjgcBhaB6jzbmax2OjJeEapIvTsvHlmw0IXKfUqY784+xr/ImUtz8RPGwYKrY1sKV88N6Qy8IRnMNSy3Z59N7NzfrtoTgJ6fCyGM3e28SB5tQUhzYQ9vrQ4OdAdZ9rPhTpR1oyjymotJXFAU4sKAqsa
    GHCR_USER: AgCL9XxG5kHF/KqSF5V4oVRFcjhLRDb4gHeCaNR/qrVmqTwItAEJnwNQ4VzzVaf77Y75HxOtu98gcdzyGKWkeAKpKQWbSxpLkVPGBvlhvSkAJd6fGc7RP9EiM9ojEUI/lStDehb+2QyObjKJ2bfviPrxGayduBEPPWQsnmjMhTpuIcT7xIra8vVEG/I3wrx60vV1a9MXufIJiO7d5Qu24mQ2KwXjIH1OMrj7SROv7S/sg35PAceEKIlYR5Cv/q4pvqFmSbOjckCUzG6b9QIugYr/fLUbZiY52p8Qoj3SdzIW8meC+79aSX6U2OtscUkGXs/6AG1NYyniR7Ci7q648/LCjauYLiB1B+lxg+q8J70da+D7R8tkUkYFA/8WSk3LlwwMP0qGOlL2SXYOr6e5nRhNlibDRznwfnUIBdNuCyAipVLJt/2+jsBrKi0vf7ne/dOGcWPSDNmS83oINiW4afnkmHP6Y2GNj0d5nzu8+NrOEsns76hA1gmlw4nN33t8nzIhSn62+BkRV/j6W0KAfzFwpxAUa6AInt3TWHxu/COJmG6VyS3OaAWIPkowQJo5+tCOw6qXthkqyD51tIcwRANA93MS0Ut4zjeHuMWKPefztosZD9oeEwIPMP1k3pvMGx5DH7PZGj9UGTTQjciXywQfNrp+MUo/zJvXzZ3uPSdZvIEYg1Sl4Wv3caqnFDSlVskIXgZNteUZdEcg12fLfM61
  template:
    metadata:
      name: ica-exam-sim-ghcr
      namespace: ica-exam-sim
