---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ica-exam-sim-pull-secret
  namespace: ica-exam-sim
spec:
  encryptedData:
    .dockerconfigjson: AgDYZ0bGt9ZyTqTR5vyKXr/vS4qHkI4XS02KPJUm842updyIgE+uHZjWdNxvDHgqZ/2+AyZ+pHUnMVXqzCSU/lqz88qgvpJ+FwBaFj3Feng0Oib0gv7k/UJm8FjTBt76sPyKzf80kzJQxmNPm9QDLoK8LETTQiC2bboLzOmMIbBPtfpVLfM6o8gUsIF7/kBTTVxTE3kE9GKFYmFvgiAzdwuXb+BWbYHh16PwqjeSiMJLIGiIfv8oMZo/tDxcfPVl407LDFvoJg5/2O0fkrSqJ5/g7OVKJfIO7cIy1teStiAaaDcpuUgZ3YWl+YcryTPjrK3ljrNQB5Q/5PtmbkT9nVxoGxGJCMamJakFX7KNqn37NF7HGK5MkpUy0IBf+yVtEsEzv1BBM/ONuK5sedHYe4adu6eNcTClgD+yCZ3NXqnJI4QFpP2Ozi27UP1OtGW0r+DbGug3juX8gYdTo3wnT+7kwOaQftGQHhzBiK10r/7qDJLzIMD6IWdEzMT/VCFewfGUlg7t9U/PrM1qC2PeXUD/H1eEXpnlJshFcXugnqfPOC+zKc8zP10LmMCzYFYYQpQzSsd6GzGHa/dexGqbzqRzb0P76iHRi/+1QbRvqheSZWupDh/qJR4pC6ZCLQy8+XlMoIejSS84praXcqDnfCoQ8omP5bM8jfz9yhlIfJstqju/8x7xDMSIJUkdVxIJup8I4SpDfdbEZzhzmHGQ2emDLIllU4b4WDDbNIDBPzzpTIhqcQb/Fc1bVQicSvzMwqYfTJe3jOlJnTEfmCOlISYCHOA0VL7nriekTnQMqW9Gy9OsVfa9t0wBcEqCbi69OIBzEw1GniMaA5OqNPNd0qfdvbU5SfkFnLjScczDoZLkkqETpaImBtZtuphlReiGa6Zy6EV62kjXA0XM5/BR4GilvWnYx+eHJu+hje8iYUXKgdO4AquxPTqh54kT38rXgPVY
  template:
    metadata:
      name: ica-exam-sim-pull-secret
      namespace: ica-exam-sim
    type: kubernetes.io/dockerconfigjson
