---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ckad-exam-sim-ghcr
  namespace: ckad-exam-sim
spec:
  encryptedData:
    GHCR_TOKEN: AgAVeDc2ZR6W8uCvs7Xq2Gy/94KoTIMq98Goao+CHqBx28X5mr8oz2YPAK9A0EtldOm1Vd4xXQWEO8WUd5feJP5IzgaKmLr3FgKEvIvwkg9b89ILc9WLqGgC4BQj1smYRZuHdRJavr92LvdCJjL+zuyUUVXv/pxJ4edpWN4xoR9MTNYSo2czs+yUOga6fPPC9BzCnISAI2TQ88vvM6DwiE+xCdAeu/vE+y5TSQytKtdXYjzTWSNYQ1ObsLtXto/3iB1u8rykHe3qwh/avG1NBpBvqQO1HlJ/pJPSRy/Qt0uz9I73Q+s1WvOUX7ypeG0ZqeMVsGT2GTNqqSWRDJwVGvTgozXJrIz/kP+Id3xwHHN9fZA4Ec82wigIz97WbsppGpXpin5zqkz+MXK0AbtO/INwBDM1y1BHm4NAUALsZe3S4QolXRiWIiwxdP5xiJcuaADY/EoH9UpJsgV/xOJhTsSgajM50UkfKJtvWdO3zI1zw+akiMCMqLBucoh2B9WXVHWtFsoJaBj2bRQY7G6S+Y0rxuwQSMauy1kNtHIvKTsGV9+nPsRlEe4s0lNibwcpD3vf0mwDhdDI7yDpS9Mh+Qvy+NwEArG4FR7sQB+okmilT7oftXT/DL9mA7wFPfsIbjRXuBozzq9XMF6DnmJljyGfseyd+LXLrnVlAN7Fxjkd46lR3MBlr5oolR25nwnKyI7RCK5DF98ETUpGV4u2IjRjbXMKknpMbCsTv+tpjVg0nLyeIO1R5FY4
    GHCR_USER: AgBXYZlW6FqkcjyVW+0OWUsulkC2L8Oj/euaWYDhC5yhatwT49DXt5B8xKXZQ7t/dhTJemqCMonebAjygKOtuCp4yAWVaKY2ZWfw1IGYbfMWRRogfZzxN7caJVkevcirxkJYJioSHcC9r+vpBT9rD6xqPwXUtT3VHkAVJW4W/dlUfgJlCM6lZO0Rs26UbB5SWn+CmrRXsW2KGa3ieqD+sx1qTJ4vJMYpG9JRsxugK1RYeOI641npWuuJjJlHU018i6nZSdUNwh2L2/U7vHDjbx76Wx5PGdu6ZQp7quX/zdR8rFwpmN2FEQ7KZ0eeRRs9Rrx09nN4TZJYA3ullIjKX1O0Bn+0WkBFzu+F9tETqrHdwppO+3Iv5e1XV78d9NT6QlYj8GMu5wK8s2t0wRUXXBrRXl7b5TQGdZ4r4pEm0eWcm1V0oWiHZD1+IDxJjYyy23lAe9BnLvJpjCJBl1epKIgHrvr70mVAU7zRETkK7K+8FTPChN4yyAhYQEN3s6+53vzotNXfGOpKJsgKE2GIqN/a3r/3klJWJk+qLGtHq3fTYz+rTtEclDmdwYKejgZ1fwCwLUgq3zASmuROy99G9449bPxVfdmX2Hq7sar44GgrLdFaH3V8gabJBKIg8DggrFX7xXyi6lzElEyVUj0kkV+V/jylJ/zB3iMpJftE2K1/8JZCh24WxR8v8dnofEZ6Uci0LdqlLomU94hHiDbhbd74
  template:
    metadata:
      name: ckad-exam-sim-ghcr
      namespace: ckad-exam-sim
