---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ckad-exam-sim-pull-secret
  namespace: ckad-exam-sim
spec:
  encryptedData:
    .dockerconfigjson: AgDJf2S2i5MNs8J2aJkdKccR/WBQ50ERXbUEfkaeeQ7+1uUuln/Zx5YVnE6pRepCVc0b1Oergp2FP192IZhWzQLF1dsGLuFadUx0u/BnGd89Q2pgnIXFsVJZbpSZeqzK0mDlwhZLHEl6i3jW5M2sQkFUmD/PgHSoGoNiJJHYdKkkaL1P6/Ksq3BZE/TIZLXwHC2nHWZoi3m4m1FKl2uPj6ovreNWWYqtqZXqRSs8ueCFpc3F9TydUb8aOa+AKUt+/uAr9h8MTn8jyECaxp1Hwl7RB56GWq/P96odSOj+XlaDr3ui+yhZZYaWFA3uGqV0Msd2VRPBevMTAqSoq8VEcibI903oC4KT8zcKN/KF5dm8TJa2Ggvx0hBWAm7LNyQTVfSP7VnZhYVLCnRIoe+UBqOR7s/pw9SkPoYAIuFfLCSa7WpcVaTJAMeJJGy/ETiUXoDtF8OWUdh/cmHJ6r0J6k2xPl2/9hRpMYZd1uMm4PhJ10lRwpscheostxBjpAHnCewsLRbzMsrTTpM5A1NVKjyH2sINKQHL0qn7ZKucGmeJ/dGAAHKxK7K0kUKgVy7iu9KijgHqmO/3hwezvxSHq2zpH7PatyCgNAJQ7ODKR9Q+rsWFgtlZ3uN++hLFobriDHkfC+8mOjP5XBNijo7KvrWRdnl5WoX0Pj2OXnlpTkwIAkbSMh8SXOBa/Zfwn18XVE1XI0mk1j8InXCR3L43aaSQTF13YvUv1FfYUhHLfRTXKT42OjKXV0UXaUr/FXYELec6Z0G44yA0K0H+tBReEN5Lt8ZHRzIGHXPlUA1liW+z4+bb14V2bShtAAeMBvNRbC2rMQJw/nlW/wDJ6BcOFHOKUgefy9CPCTEby1+QDX94kXktH1FK+nM0DtXaCB53UsG59JRCC+YS1VOemKsTu9Ty5CkS3jA36aSEdgmo2rkq0nT1U97qdOHerLj3G6VJqrJ6
  template:
    metadata:
      name: ckad-exam-sim-pull-secret
      namespace: ckad-exam-sim
    type: kubernetes.io/dockerconfigjson
